[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app --host 0.0.0.0 --port $PORT --workers 2 --timeout 60"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
FLASK_DEBUG = "false"
